name = "nogi-ical-worker"
main = "src/index.ts"
account_id = "015a5ae11bb1c06849144ec1cba87b14"
workers_dev = true
compatibility_date = "2022-02-23"
node_compat = true

[build]
command = "npm install && npm run build"
